version: '3'
services:
  app:
    build: .
    ports:
      - '5001:5000'
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/backendDB?authSource=admin
      - JWT_SECRET=secret-hackathon-key
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=backendDB
    command: ['mongod', '--auth']
